---
version: "2"
checks:
  file-lines:
    enabled: false
  similar-code:
    enabled: true
    config:
      threshold: 3
  identical-code:
    enabled: true
    config:
      threshold: 3
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
plugins:
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
