version: 2.1
orbs:
  shiftleft: shiftleft/shiftleft@1.0.6

workflows:
  version: 2.1
  run-sast-scan:
    jobs:
      - shiftleft/analyze:
          app: dvna
          target: .
          language: js
          cpg: true
