version: 2.1
jobs:
  nodejsscan:
    docker:
      - image: 'circleci/python:3.8.4'
    working_directory: ~/dvna
    steps:
      - checkout
      - run: mkdir ~/dvna/artifacts/
      - run: pip3 install njsscan
      - run: njsscan . --json -o ~/dvna/artifacts/njsscan.json
      - store_artifacts:
          path: ~/dvna/artifacts

workflows:
  version: 2.1
  run-sast-scan:
    jobs:
      - nodejsscan
