version: 2.1
jobs:
  nodejsscan:
    docker:
      - image: 'circleci/python:3.8.4'
    working_directory: ~/workspace
    steps:
      - checkout
      - run: mkdir ~/workspace/artifacts/
      - run: pip3 install njsscan
      - run: njsscan . --missing-controls  --sonarqube -o ~/workspace/artifacts/njsscan.json
      - store_artifacts:
          path: ~/workspace/artifacts/njsscan.json

workflows:
  version: 2.1
  run-sast-scan:
    jobs:
      - nodejsscan
