version: 2.1
jobs:
  nodejsscan:
    docker:
      - image: 'circleci/python:3.8.4'
    steps:
      - checkout
      - run: pip3 install --upgrade njsscan
      - run: njsscan .

workflows:
  version: 2.1
  run-sast-scan:
    jobs:
      - nodejsscan
