version: 2.1
orbs:
  shiftleft: shiftleft/shiftleft@1.0.6

jobs:
  shiftleft:
    machine: true
    working_directory: ${CIRCLE_WORKING_DIRECTORY}
    steps:
      - checkout
      - shiftleft/analyze:
          app: dvna
          target: ${CIRCLE_PROJECT_REPONAME}
          language: js
          cpg: true

workflows:
  version: 2.1
  run-sast-scan:
    jobs:
      - shiftleft
